plugins {
    id 'fabric-loom' version '1.6.12'
    id 'maven-publish'
}

group = 'com.refinedmods'
version = project.findProperty('mod_version') ?: '1.12.4-fabric.1'

base {
    archivesName = 'refinedstorage'
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    minecraft 'com.mojang:minecraft:1.20.1'
    mappings loom.officialMojangMappings()
    modImplementation 'net.fabricmc:fabric-loader:0.19.5'
    modImplementation 'net.fabricmc.fabric-api:fabric-api:0.92.12+1.20.1'
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand 'version': project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 17
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    withSourcesJar()
}

jar {
    from('LICENSE.md') {
        rename { "${it}_refinedstorage" }
    }
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            from components.java
        }
    }
}
